### ISSUE TITLE
季語のバリューを計算するロジックを考える

### ISSUE THREAD

**Issue by ulxsth** [ulxsth/Haiku-yomi#2]
# やりたいこと
季語（たとえば「春」「夕立」「クリスマス」）について、それぞれのバリューを計算するロジックを考える！
考えたものをJS（もしくはTS）で実装して、このIssueのスレッドに張り付けるなどしておいてほしい

## たとえば
- 文字数
- 見た目が強そう
など

実装できるなら何でもいいと思います

**Comment by ulxsth** [comment]
例えばJSで実装する場合、

- 文字列をひとつ受け取り
- その文字列が示すバリューの値（整数）を返す

関数を実装することになる

```js
function calcSeasonWordValue(seasonWord) {
  # いいかんじのロジック
  return value;
}
```

**Comment by massan02** [comment]
ごめん遅くなった

アイデアとしては、ある特定の組み合わせで点数アップ（海水浴・ビーチボール）とかいいと思う　クソデカとの相性もいいし

基本的には文字数判定でいいと思う

ごめんあと今日夜しか活動できん

**Comment by ulxsth** [comment]
- ある特定の組み合わせで点数アップ（海水浴・ビーチボール）とかいいと思う

ありだけど実装コストが高すぎる

- 基本的には文字数判定でいいと思う

これでいいかな～　
計算方法はどうする？加算か乗算かとか

**Comment by massan02** [comment]
基本は加算で季節の相性、名句ボーナスで乗算とかどう？

**Comment by ulxsth** [comment]
そのへんは #3 とか #4 で考えることかな
とりあえず季語は文字数だけで実装しようか

**Comment by massan02** [comment]
`function calcSeasonWordValue(seasonWord) {
    const judgeSeasonWord = seasonWord;
    let value = 0;

    value += judgeSeasonWord.length;
    return value;
  }`

これで大丈夫？

**Comment by massan02** [comment]
`
function calcSeasonWordValue(seasonWord) {
    const judgeSeasonWord = seasonWord;
    let value = 0;

    value += judgeSeasonWord.length;
    return value;
  }
`

**Comment by ulxsth** [comment]
いったんこれでSeasonWordクラスに実装して、仕様を追加するときはこの関数をいじる形にしよう
