### ISSUE TITLE
句のバリューを計算するロジックの検討

### ISSUE THREAD

**Issue by ulxsth** [ulxsth/Haiku-yomi#3]
# やりたいこと
#2 で考えた季語のロジックをもとに、上中下の句それぞれの計算ロジックを検討する

## 例
「古池/や」「蛙/飛び込む」「水/の/音」
- 季語は「蛙」のみ

# 考慮すべきこと
- ロジックの実現可能性
  - 実現できない可能性の高いものはNG
  - 実現自体は可能でも、開発コストが明らかに高いものも要注意
- 季語以外の単語の扱い
  - 計算に含めるか？ 含める場合はどのようにする？

**Comment by massan02** [comment]
追加すると良さそうなこと
・季語以外の単語は1文字ごと1点
・季語は文字数×ボーナスで加点

今のところは季語の文字数のみでの判定だから優先しなくて大丈夫そう？
